NAME := openlibm
SRCS += $(shell find ./src -name "*.c")
INC_DIR += $(shell realpath ./src) \
						$(shell realpath ./include)
INC_DIR += $(AM_HOME)/libs/klib/include

include $(AM_HOME)/Makefile.lib

